---
Name: elementalgrid
After:
  - 'elemental'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'thewebmen/silverstripe-elemental-grid:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'thewebmen/silverstripe-elemental-grid:client/dist/styles/bundle.css'

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\BaseElementExtension
