---
Name: elementalgrid
Before:
  - 'elemental'
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - twm/silverstripe-elemental-grid

DNADesign\Elemental\ElementalEditor:
  extensions:
    - TWM\ElementalGrid\Extensions\ElementalEditorExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - TWM\ElementalGrid\Extensions\BaseElementExtension

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - TWM\ElementalGrid\Extensions\ElementalAreaExtension
