---
Name: elementalgrid
After:
  - 'elemental'
---

DNADesign\Elemental\ElementalEditor:
  extensions:
    - TWM\ElementalGrid\Extensions\ElementalEditorExtension

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - TWM\ElementalGrid\Extensions\BaseElementExtension

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - TWM\ElementalGrid\Extensions\ElementalAreaExtension
