---
Name: elementalgrid
After:
  - 'elemental'
---
SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - thewebmen/silverstripe-elemental-grid

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'thewebmen/silverstripe-elemental-grid:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'thewebmen/silverstripe-elemental-grid:client/dist/styles/bundle.css'

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\ElementalAreaExtension

DNADesign\Elemental\Models\ElementContent:
  extensions:
    - TheWebmen\ElementalGrid\Extensions\ElementContentExtension

DNADesign\Elemental\Models\BaseElement:
  inline_editable: false
  extensions:
    - TheWebmen\ElementalGrid\Extensions\BaseElementExtension

TheWebmen\ElementalGrid:
  default_column_size: 12
  default_viewport: 'MD'
  css_framework: 'bulma'

TheWebmen\ElementalGrid\Pages\GridPage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
